version: '3.8'

services:
  backend:
    build:
      context: ../Backend
      dockerfile: Dockerfile
    ports:
      - "7123:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  frontend:
    build:
      context: ../Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
